apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-follower
  labels:
    app: redis
    role: follower
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: follower
  template:
    metadata:
      labels:
        app: redis
        role: follower
    spec:
      containers:
      - name: redis-follower
        image: redis:latest
        # Removed the volumeMounts and volumes related to the configMap
