apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: recipe-generator-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recipe-generator
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
